
baseURL = "/"

languageCode = "en"

title = "Kendo Debug Project"

disableKinds = ["RSS", "taxonomy", "taxonomyTerm", "sitemap"]

theme = "canada.ca"

defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 10
  [languages.fr]
    contentDir = "content/fr"
    languageName = "Français"
    weight = 20
